import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import { PawPrint } from "@phosphor-icons/react/dist/ssr";

export const metadata = {
  title: "Javabot Plus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-24 h-screen">
        <nav className="h-16 top-0 fixed w-screen bg-slate-200 flex justify-between items-center px-8 shadow-md">
          <div className="font-bold text-xl flex gap-3 items-center">
            <PawPrint size={32} weight="fill" /> Javabot Plus
          </div>

          <div className="flex justify-center items-center gap-6">
            <div className="gap-3 flex divide-x-2">
              <Link
                className="rounded-lg hover:bg-slate-300 p-2 transition-all"
                href="/"
              >
                Home
              </Link>
              <Link
                className="rounded-lg hover:bg-slate-300 p-2 transition-all"
                href="/loja"
              >
                Loja
              </Link>
              <Link
                className="rounded-lg hover:bg-slate-300 p-2 transition-all"
                href="/animals"
              >
                Animais
              </Link>
            </div>
            <Image
              className="w-10 rounded-full"
              width={128}
              height={128}
              src="/avatar-logo.jpeg"
              alt="Account Photo"
            />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
