import "./globals.css";
import NavBar from "../components/NavBar";
import { ReactNode } from "react";

export const metadata = {
  title: "Javabot Plus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="pt-24 h-screen">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
