import "./globals.css";
import NavBar from "../components/NavBar";
import { ReactNode } from "react";
import { SessionProvider } from "../lib/auth";

export const metadata = {
  title: "Javabot Plus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className="pt-24 h-screen flex flex-col items-center">
          <NavBar />
          <div className="container">{children}</div>
        </body>
      </html>
    </SessionProvider>
  );
}
